// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Emergence.Common.Model
{

    public class Aqi
    {

        [JsonProperty("so2")]
        public string So2 { get; set; }

        [JsonProperty("so224")]
        public string So224 { get; set; }

        [JsonProperty("no2")]
        public string No2 { get; set; }

        [JsonProperty("no224")]
        public string No224 { get; set; }

        [JsonProperty("co")]
        public string Co { get; set; }

        [JsonProperty("co24")]
        public string Co24 { get; set; }

        [JsonProperty("o3")]
        public string O3 { get; set; }

        [JsonProperty("o38")]
        public string O38 { get; set; }

        [JsonProperty("o324")]
        public string O324 { get; set; }

        [JsonProperty("pm10")]
        public string Pm10 { get; set; }

        [JsonProperty("pm1024")]
        public string Pm1024 { get; set; }

        [JsonProperty("pm2_5")]
        public string Pm25 { get; set; }

        [JsonProperty("pm2_524")]
        public string Pm2524 { get; set; }

        [JsonProperty("iso2")]
        public string Iso2 { get; set; }

        [JsonProperty("ino2")]
        public string Ino2 { get; set; }

        [JsonProperty("ico")]
        public string Ico { get; set; }

        [JsonProperty("io3")]
        public string Io3 { get; set; }

        [JsonProperty("io38")]
        public string Io38 { get; set; }

        [JsonProperty("ipm10")]
        public string Ipm10 { get; set; }

        [JsonProperty("ipm2_5")]
        public string Ipm25 { get; set; }

        [JsonProperty("aqi")]
        public string Aqi { get; set; }

        [JsonProperty("primarypollutant")]
        public string Primarypollutant { get; set; }

        [JsonProperty("quality")]
        public string Quality { get; set; }

        [JsonProperty("timepoint")]
        public string Timepoint { get; set; }

        [JsonProperty("aqiinfo")]
        public Aqiinfo Aqiinfo { get; set; }
    }

}
