// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Emergence.Common.Model
{

    public class Aqiinfo
    {

        [JsonProperty("level")]
        public string Level { get; set; }

        [JsonProperty("color")]
        public string Color { get; set; }

        [JsonProperty("affect")]
        public string Affect { get; set; }

        [JsonProperty("measure")]
        public string Measure { get; set; }
    }

}
