// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Emergence.Common.Model
{

    public class Daily
    {

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("week")]
        public string Week { get; set; }

        [JsonProperty("sunrise")]
        public string Sunrise { get; set; }

        [JsonProperty("sunset")]
        public string Sunset { get; set; }

        [JsonProperty("night")]
        public Night Night { get; set; }

        [JsonProperty("day")]
        public Day Day { get; set; }
    }

}
