// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Emergence.Common.Model
{

    public class Index
    {

        [JsonProperty("iname")]
        public string Iname { get; set; }

        [JsonProperty("ivalue")]
        public string Ivalue { get; set; }

        [JsonProperty("detail")]
        public string Detail { get; set; }
    }

}
