// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace Emergence.Common.Model
{
    public class Weather : WeatherBase
    {

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("cityid")]
        public string Cityid { get; set; }

        [JsonProperty("citycode")]
        public string Citycode { get; set; }

        [JsonProperty("updatetime")]
        public string Updatetime { get; set; }
    }

    public class WeatherBase
    {
        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("week")]
        public string DayOfWeek { get; set; }

        [JsonProperty("weather")]
        public string WeatherName { get; set; }

        [JsonProperty("temp")]
        public string Temp { get; set; }

        [JsonProperty("temphigh")]
        public string TempHigh { get; set; }

        [JsonProperty("templow")]
        public string TempLow { get; set; }

        [JsonProperty("img")]
        public string Img { get; set; }

        [JsonProperty("winddirect")]
        public string WindDirect { get; set; }

        [JsonProperty("windpower")]
        public string WindPower { get; set; }

        [JsonProperty("windspeed")]
        public string WindSpeed { get; set; }

        [JsonProperty("daily")]
        public WeatherBase[] Daily { get; set; }

        [JsonProperty("day")]
        public WeatherBase Day { get; set; }

        [JsonProperty("night")]
        public WeatherBase Night { get; set; }
    }

}
