// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Framework;
using Newtonsoft.Json;

namespace Emergence.Common.Model
{
    public class Weather : WeatherBase
    {

        [JsonProperty("city")]
		public virtual string City { get; set; }

        [JsonProperty("cityid")]
		public virtual string Cityid { get; set; }

        [JsonProperty("citycode")]
		public virtual string Citycode { get; set; }

        [JsonProperty("updatetime")]
		public virtual string Updatetime { get; set; }
    }

    public class WeatherBase: NotificationObject
    {
        [JsonProperty("date")]
        public virtual string Date { get; set; }

        [JsonProperty("week")]
		public virtual string DayOfWeek { get; set; }

        [JsonProperty("weather")]
		public virtual string WeatherName { get; set; }

        [JsonProperty("temp")]
		public virtual string Temp { get; set; }

        [JsonProperty("temphigh")]
		public virtual string TempHigh { get; set; }

        [JsonProperty("templow")]
		public virtual string TempLow { get; set; }

        [JsonProperty("img")]
		public virtual string Img { get; set; }

        [JsonProperty("winddirect")]
		public virtual string WindDirect { get; set; }

        [JsonProperty("windpower")]
		public virtual string WindPower { get; set; }

        [JsonProperty("windspeed")]
		public virtual string WindSpeed { get; set; }

        [JsonProperty("daily")]
		public virtual WeatherBase[] Daily { get; set; }

        [JsonProperty("day")]
		public virtual WeatherBase Day { get; set; }

        [JsonProperty("night")]
		public virtual WeatherBase Night { get; set; }

		[JsonProperty("sunrise")]
		public virtual string SunRise { get; set; }

		[JsonProperty("sunset")]
		public virtual string SunSet { get; set; }
    }

}
